GliderVarioPortIOException: errno value and string got lost
errNo and errStr were not added to whatString.
Therefore std::exception::what() did not return the errno value and
string description for this class and descendants.